services:
  postgres:
    image: postgres:16-alpine
    container_name: os-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-orders}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-orders}
      POSTGRES_DB: ${POSTGRES_DB:-orders}
    ports:
      - "5432:5432"
    volumes:
      - os_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-orders} -d ${POSTGRES_DB:-orders}"]
      interval: 5s
      timeout: 3s
      retries: 20

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: os-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  os_pgdata:
